[package]
name = "trails_cli"
version = "0.1.0"
edition = "2024"
default-run = "trails_cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
trails = { path = "../trails" }