name: Deploy
on:
  push:
    branches:
      - main

env:
    VITE_BASE_URL=https://trails.jamesbaum.co.uk
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libudev-dev -y
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          # https://zellwk.com/blog/github-actions-deploy/
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Add to known hosts
        # SSH_HOST is the IP of the digital ocean dropley
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Copy files
        run: rsync -avz ./target/release/trails_web ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:${{secrets.DEST_FOLDER}}

  deploy-frontend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: cd web/frontend && npm i
      - name: Build
        run: cd web/frontend && npm run build
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          # https://zellwk.com/blog/github-actions-deploy/
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Add to known hosts
        # SSH_HOST is the IP of the digital ocean dropley
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy
        run: rsync -avz ./web/frontend/dist ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:${{secrets.STATIC_FOLDER}}